services:
  postgres:
    image: postgres:15
    container_name: myskilledcv-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myskilledcv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myskilledcv-net

volumes:
  postgres_data:

networks:
  myskilledcv-net:
    driver: bridge